### ISSUE TITLE
Free converter is not available now

### ISSUE THREAD

**Issue by toxaus** [zhikiri/currency-converter#2]
Seems this one is die

***currency-converter/CurrencyConverter/Converters/Free.php***

**Comment by zhikiri** [comment]
@toxaus the provider is alive, just API was changed. New version of the API <a href="http://www.freecurrencyconverterapi.com/convert_currencies">here</a>.
I will fix it soon.

**Comment by zhikiri** [comment]
Removed Free converter in last merge
